### ISSUE TITLE
Decisão de trabalho final 

### ISSUE THREAD

**Issue by Dkmister** [Dkmister/EulerianVM#1]
Dentre as opções:
- [ ] **The Visual Microphone: Passive Recovery of Sound from Video** : http://people.csail.mit.edu/mrub/VisualMic/
- [ ] **AudeoSynth: Music-Driven Video Montage** : https://zichengliao.github.io
- [ ] **Automated Video Looping with Progressive Dynamism** : https://zichengliao.github.io
- [ ] **Artistic style transfer for videos** : https://arxiv.org/abs/1604.08610
- [x] **Eulerian Video Magnification for Revealing Subtle Changes in the World** : http://people.csail.mit.edu/mrub/papers/vidmag.pdf

**Comment by Dkmister** [comment]
@pfpimenta pode comentar o que tu acha importante ressaltar nas escolhas.

Os **prós** e **contras** das escolhas, o que seria melhor de fazer, as razões.

**Comment by pfpimenta** [comment]
decidir entre
Artistic style transfer for videos : https://arxiv.org/abs/1604.08610
e
Eulerian Video Magnification for Revealing Subtle Changes in the World : http://people.csail.mit.edu/mrub/papers/vidmag.pdf

**Comment by Dkmister** [comment]
Issue fechado.
Já decidido que será sobre Eulerian Video Magnification.
